### ISSUE TITLE
【咨询】在自定义的handle里通过CseAsyncRestTemplate发送请求会是一个死循环吗？

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-java-chassis#1107]
如标题。

**Comment by wujimin** [comment]
default handler chain: h1,h2,h3
when microservice-a invoke microservice-b, will execute h1->h2->h3
in h2, invoke microservice-c, still will execute h1->h2->h3

so, yes, it's a infinite loop.

you can choose one of the solution:
- give a special chain for microservice-c in microservice.yaml, eg:
```
  handler:
    chain:
      Consumer:
        default: h1,h2,h3
        service:
          microservice-c: h1,h3
```
- do not invoke microservice-c in h2 when target is microservice-c 
```
    if (invocation.getMicroserviceName().equals("microservice-c")){
      invocation.next(asyncResp);
      return;
    }
```
