### ISSUE TITLE
 unknown rest exception.

### ISSUE THREAD

**Issue by walker-dead-cave** [apache/servicecomb-java-chassis#1288]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [device-manager.to-ief-edge.deviceStatusChangeConfig]. Parameter is [deviceConfigResponseDto]. Processor is [body].]

 ConstraintViolationExceptionToProducerResponseConverter implements ExceptionToProducerResponseConverter<ConstraintViolationException>

json格式校验异常无法被上面的异常处理捕获，请问怎样可以捕获这个异常，然后进行自定义返回

**Comment by liubao68** [comment]
使用Handler进行全局异常处理也是一个方案。

```
MyHandler imeplements Handler {
   handle -> { try {} catch(Exception) {}}
}

servicecomb:
  handler:
    chain:
      Consumer:
        default: myhander, xxx...
      Provider: 
        default: myhander,xxx...
```
