### ISSUE TITLE
Question of Distributed Tracing

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/servicecomb-java-chassis#1365]
I did follow the steps in the documentation.

http://servicecomb.apache.org/docs/quick-start-advance/distributed-tracing/

 just add something for my ZipKin

calcutor
```
servicecomb:
  handler:
    chain:
#      Consumer:
#        default: tracing-consumer
      Provider:
        default: tracing-provider
  tracing:
    collector:
      address: http://192.168.1.11:9411
```

webapp
```
servicecomb
   tracing:
     collector:
       address: http://192.168.1.11:9411
```

and it not working,

JDK: 1.8
project:
``
org.apache.servicecomb.samples.bmi
``
