### ISSUE TITLE
SpringBoot2+SpringMVC集成的两个问题

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1402]
1、官方文档宣称只是支持SpringMVC的开发模式，但是某些特性不支持，那如下特性我要怎么实现？
- 基于@ControllerAdvice同一接口返回格式，如：{"errorCode":"0","result":{"username":"nick"}}
- 基于SpringSecurity注解的权限校验，如：@hasRole("admin")

2、ServiceComb是否支持SpringBoot2的WAR模式，并且同时使用SpringMVC和ServiceComb能力？
如：
- /rest-mvc/* 纯SpringMVC路径，可以使用SpringMVC的所有能力
- /rest-servicecomb/* ServiceComb服务接口

目前我验证的结果是：添加@RestSchema的接口正常，但是纯SpringMVC的接口都无法访问，信息如下：

> [2019-11-20 16:26:15]-[http-nio-8081-exec-3]-[ERROR]-[org.apache.servicecomb.common.rest.locator.OperationLocator.locate:72] locate path failed, status:Not Found, http method:GET, path:/demo/rest-ui/person/, microserviceName:adc-demo

```
APPLICATION_ID: adc-demo
service_description:
  name: adc-demo
  version: 0.0.3
  description: ADC Demo
  environment: development
servicecomb:
  service:
    registry:
      registerPath: true
      address: http://127.0.0.1:30100
  rest:
    address: 0.0.0.0:8081
    server:
      compression: true
    request:
      timeout: 30000
    servlet:
      urlPattern: /*
  provider:
    rest:
      scanRestController: false
```
