### ISSUE TITLE
前后台服务都注册在sc上，使用cse访问，该如何配置tsl

### ISSUE THREAD

**Issue by zhangbeiyuan-hw** [apache/servicecomb-java-chassis#1609]
当前所有服务都注册在sc上，前台服务也是通过gateway的方式发布的静态页面，vue中通过cse方式调用后台服务；想请教一下，tsl应该配置在每个servicecomb上？还是配置在servicecenter上？或者两个地方都要配置。
servicecomb中没有配置publishAddress地址，我理解客户端不能通过ip直接访问服务，只能通过servicecenter  cse方式访问；

**Comment by heyile** [comment]
服务中心只做 服务发现. 实际调用的时候, 是 conusmer端 只是去 服务中心查询 Provider 地址. 然后是 consumer  直接调用 provider.

**Comment by heyile** [comment]
所以. 想配置 tsl , 只需要自己的实例配置 tsl 就好了, 不用管服务中心.

http://1v96us.coding-pages.com/docs/java-chassis/zh_CN/security/tls/

**Comment by heyile** [comment]
支持设置 publishAddress. 

```yaml

servicecomb:
  service:
    registry:
      address: http://127.0.0.1:30100
  rest:
    address: 0.0.0.0:8080?protocol=http2


```
