### ISSUE TITLE
跟SpringMVC共用的时候会存在路径冲突

### ISSUE THREAD

**Issue by zhufeizzz** [apache/servicecomb-java-chassis#1622]
```
@RestSchema(schemaId = "RepeatServiceA")
@RequestMapping(path = "/rest/repeat-a")
public class RepeatService 

@RestController("RepeatServiceB")
@RequestMapping(path = "/rest/repeat-a")
public class RepeatService {
```
比如下面这两种，因路径冲突SpringMVC会报“Ambiguous mapping”异常。即使CSE和SpringMVC分别声明了独立的根路径。这种问题有什么解决建议吗？
```
spring:
  mvc:
    servlet:
      path: /ui
servicecomb: 
    servlet:
      urlPattern: /cse/*
```
