### ISSUE TITLE
microservice.yaml支持include properties，并支持占位符替换property

### ISSUE THREAD

**Issue by shijinkui** [apache/servicecomb-java-chassis#1750]
external_conf.properties
```
app_name=xxxx
```
再microservice.yaml里include external_conf.properties，替换yaml中的变量占位符。

```
!include external_conf.properties
APPLICATION_ID: ${app_name}
service_description:
  name: fooService
  version: 0.0.1

servicecomb:
  rest:
    address: 0.0.0.0:8080
```

这样能够很容易做dev/prod环境配置。如果多环境直接操作yaml，就要维护本地开环境的配置yaml和yaml.tmpl模板。
