### ISSUE TITLE
edgeservice路由配置，配置项名称导致路由不可用

### ISSUE THREAD

**Issue by cxybyte** [apache/servicecomb-java-chassis#1758]
路由配置如下：

```
face-track-manager:
              prefixSegmentCount: 0
              path: "/v1/.*/video-analysis/face-track.\*"
              microserviceName: face-track-manager
              versionRule: 0.0.0-2.0.0
video-analysis-manager:
              prefixSegmentCount: 0
              path: "/v1/.*/video-analysis.\*"
              microserviceName: video-analysis-manager
              versionRule: 0.0.0-2.0.0_
```

1、如上配置，若配置项名称为微服务名face-track-manager会导致路由下发到video-analysis-manager服务中。
2、若配置项名称为test等其他名字，路由会正常下发到face-track-manager服务中。
测试路由为：
http://127.0.0.1:3330/v1/123/video-analysis/face-track/tasks?offset=0&limit=10
