### ISSUE TITLE
路由管理能力咨询

### ISSUE THREAD

**Issue by liukuancn** [apache/servicecomb-java-chassis#1893]
1.这里的version是否支持范围规则？  
```
          route: #路由规则
            - weight: 50 #权重值
              tags:
                version: {version1}
                app: {appId}
```
2.假如我配了如下2个路由规则，如果version2实际不存在，是不是就都会走version1？  
```
          route: #路由规则
            - weight: 50 #权重值
              tags:
                version: {version1}
                app: {appId}
          route: #路由规则
            - weight: 50 #权重值
              tags:
                version: {version2}
                app: {appId}
```
