### ISSUE TITLE
Nacos配置的数据已经获取但无法注入到项目中

### ISSUE THREAD

**Issue by zhangaijing** [apache/servicecomb-java-chassis#2049]
获取的数据:
![image](https://user-images.githubusercontent.com/16713552/98818637-cd073d80-2466-11eb-9726-8ee10a5c25fa.png)

异常:
![image](https://user-images.githubusercontent.com/16713552/98818710-e27c6780-2466-11eb-93f2-62b04baad164.png)

配置信息:

```
servicecomb:
  nacos:
    serverAddr: http://127.0.0.1:8848
    group: DEFAULT_GROUP
    dataId: manage-nacos.yaml
    namespace: public
    contentType: yaml
```

使用的包:

```
        <!-- 基础包, cse 对应 servicecomb > groupId: org.apache.servicecomb, artifactId: solution-basic -->
        <dependency>
            <groupId>com.huawei.paas.cse</groupId>
            <artifactId>cse-solution-service-engine</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.servicecomb</groupId>
                    <artifactId>config-cc</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>java-chassis-spring-boot-starter-servlet</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>solution-basic</artifactId>
        </dependency>
        <!-- end -->

        <!-- serviceComb的nacos封装 -->
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>config-nacos</artifactId>
        </dependency>
        <!-- end -->
```

**Comment by liubao68** [comment]
```
servicecomb:
  nacos:
    # if true [group].[dataId] will added as properties/yaml 
    # items prefix. Will not influence raw.
    addPrefix: false
```
试试下面的配置项.
