### ISSUE TITLE
Edge-service 配置Handler不生效

### ISSUE THREAD

**Issue by tangzhexu** [apache/servicecomb-java-chassis#2127]
使用网关转发请求，未执行Handler逻辑。
java-chassis版本2.1.3
Handler配置如下:
```
/resource/config/cse.handler.xml
<config>
  <handler id="basic"
    class="com.tellhow.cloud.gateway.handler.HttpBasicGatewayHandler" />
</config>
```
网关配置如下:
```
/resource/application.yaml
servicecomb:
  service:
    registry:
      address: xxx # CSE引擎服务注册发现地址, https或者http按照实际填写, 用户需要确定本地到注册中心地址在网络上是互通的。
  config:
    client:
      serverUri: xxx # CSE引擎配置中心地址, https或者http按照实际填写, 用户需要确定本地到配置中心地址在网络上是互通的。
  handler:
    chain:
      Consumer:
        default: basic,loadbalance
```
