### ISSUE TITLE
RPC调用处理链问题咨询

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2179]
背景介绍：
    我们的edge服务在转发REST请求时有自定义handler处理链鉴权，鉴权逻辑中某个特殊场景需要访问后端的微服务，因AsyncRestTemplate不建议使用，我们采用的是RPC方式。
问题咨询：
   鉴权处理链中访问后端服务的请求如何避免走cosumer的处理链？只需要走loadbalance处理链就可以了。
我当前的处理是对比转发和鉴权时invocation中endpoint差异，在代码中识别endpoint为空时直接跳过该处理链。麻烦提供下正版处理方法。

**Comment by liubao68** [comment]
可以给不同服务配置不同的处理链：

```
servicecomb:
  handler:
    chain:
      Consumer:
        default: internalAccess,auth,qps-flowcontrol-consumer,loadbalance
        service:
          authentication-server: internalAccess,qps-flowcontrol-consumer,loadbalance
          authentication-client: internalAccess,qps-flowcontrol-consumer,loadbalance
```
