### ISSUE TITLE
限流问题咨询

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2182]
问题描述：
    转发的REST请求会先走provider的限流策略，然后再走cosumer的限流策略。
配置项如下：

```
handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance
  flowcontrol:
    Provider:
      qps:
        enabled: true
        strategy: FixedWindow
        global:
          limit: 2147483647
    Consumer:
      qps:
        enabled: true
        strategy: FixedWindow
        global:
          limit: 10000
        limit:
          dsc-cim-service: 2
          dsc-contacts-service: 2
```

外部调用URL：

```
    /dsc-cim-service/v1/userProfileQuery
```

打点调试，发现请求会先到Provider的流控handler：
![image](https://user-images.githubusercontent.com/74586506/103601755-4db55800-4f45-11eb-808b-6d73a7f97281.png)
然后再走cusumer的流程handler：
![image](https://user-images.githubusercontent.com/74586506/103601805-69b8f980-4f45-11eb-851c-222c139fd9e8.png)
流控JAR包版本：
    handler-flowcontrol-qps-1.2.0.B017r2.jar

这个情况是我哪里配置错误吗？还是正常流程就是这个情况？
