### ISSUE TITLE
优雅停机配置不生效

### ISSUE THREAD

**Issue by ChauncyXia** [apache/servicecomb-java-chassis#2189]
java-chassis版本：1.3.1.B002.jar

microservice.yaml：

```
service_description:
  name: WiseCloudHuaweiCardService
  version: 1.0.0
  environment: development
instance_description:
  propertyExtentedClass: com.xx.xx.xx.xx.xx.cse.property.xx

cse:
  service:
    registry:
      address: http://xx.xx.xxx.xx:xxx
      instance:
        healthCheck:
          interval: 10
          times: 2
      watch: true 
  rest:
    address: 0.0.0.0:xx
  uploads:
    maxSize: 1024000  

servicecomb:
  boot:
    turnDown:
      waitInSeconds: 35
  accesslog:
    enabled: true
  executor:
    default:
      thread-per-group: 600
      coreThreads-per-group: 500
  datacenter:
    name: cn-Center
    region: cn-Region
    availableZone: cn-A
  request:
    timeout: 60000
  handler:
    chain:
      Consumer:
        default: loadbalance
```
