### ISSUE TITLE
handler的类型和作用范围

### ISSUE THREAD

**Issue by pengye1207** [apache/servicecomb-java-chassis#2211]
servicecomb支持配置handler类型有Consumer和Provider两种类型，如下配置

```yaml
servicecomb:
  handler:
    chain:
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance
      Provider: 
        default: qps-flowcontrol-provider
```

但是在[开发文档](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/intruduction/)中对于两种handler没有明确的使用范围的说明。比方说明情况下Consumer配置的handler会生效，什么情况下Provider的handler会生效。

另外希望能有个详细的调用链说明，看看一个请求完整的请求链条是怎么的？

谢谢！
