### ISSUE TITLE
EDGE性能问题咨询

### ISSUE THREAD

**Issue by huangdong-new** [apache/servicecomb-java-chassis#2229]
使用CSE SDK的EDGE server模型，在做压测时，edge => 后端服务 => edge，当前发现后端服务 => edge这条线耗时很长，有耗时几秒的。
请问下，这个是因为缺少什么配置项导致的吗？
microservice配置如下：

```
servicecomb:
  service:
    registry:
      address: https://10.33.213.172:30100
      instance:
        healthCheck:
          interval: 10
          times: 3
        watch: true
        diagnose:
          interval: 12
  rest:
    address: 10.33.213.15:8087?sslEnabled=true&protocol=http2
    server:
      verticle-count: 32
    client:
      verticle-count: 32
      connection:
        maxPoolSize: 10
      http2:
        maxPoolSize: 10
        idleTimeoutInSeconds: 60
  loadbalance:
    retryEnabled: true
    retryOnNext: 2
    retryOnSame: 0
    isolation:
      enabled: true
      enableRequestThreshold: 20
      errorThresholdPercentage: 20
      singleTestTime: 10000
  handler:
    chain:
      Provider:
        default: authTokenHandler,hiCallAuthHandler,flowControlHandler,qps-flowcontrol-provider
      Consumer:
        default: authTokenHandler,hiCallAuthHandler,flowControlHandler,loadbalance
        service:
          dsc-voip-service: voipAuthHandler,flowControlHandler,loadbalance
          dsc-trunk-service: flowControlHandler,loadbalance
  flowcontrol:
    Provider:
      qps:
        enabled: true
        strategy: FixedWindow
        global:
          limit: 10000000
```
