### ISSUE TITLE
由于编码过程中属性命名未按照驼峰命名，导致服务注册时只能成功注册第一个微服务，第二个微服务注册时提示swagger不一致。升级ServiceComb到2.1.3、2.1.5后均无法解决该问题

### ISSUE THREAD

**Issue by 936645** [apache/servicecomb-java-chassis#2275]
对比两份swagger文件之后发现是属性顺序不一致，请问这种问题怎么解决？ service center schema and local schema both are different:

 service center schema如下：

```
definitions:
  PersnCompVo:
    type: "object"
    properties:
      aab300:
        type: "string"
      aab003:
        type: "string"
      aab300D:
        type: "string"
      aab004:
        type: "string"
    x-java-class: "com.tecsun.common.response.datacerter.persnCompQuey.PersnCompVo"
```

local schema如下：

```
definitions:
  PersnCompVo:
    type: "object"
    properties:
      aab300D:
        type: "string"
      aab300:
        type: "string"
      aab003:
        type: "string"
      aab004:
        type: "string"
    x-java-class: "com.tecsun.common.response.datacerter.persnCompQuey.PersnCompVo"
```

两份文件中属性顺序不一致。
