### ISSUE TITLE
脱离注册中心是否可以使用serviceComb作为服务应用？

### ISSUE THREAD

**Issue by xiaohanfeidao** [apache/servicecomb-java-chassis#2354]
脱离注册中心是否可以使用serviceComb作为服务应用？

**Comment by wujimin** [comment]
试试zero-config  

zero-config支持多种工作模式：
* local
  单机模式，没有实例动态发现能力
  所有的服务调用，都使用第三方服务机制处理
* multicast
  使用UDP多播发送微服务注册信息
  适用于所有微服务实例都在同一个子网内的场景
  每个微服务实例都相当于是一个服务中心实例

```yaml
servicecomb:
  service:
    zero-config:
      enable: true
      mode: multicast
      heartbeat:
        interval: 30s
        lost-times: 3
      pull-interval: 3s
      multicast:
        address: 0.0.0.0:6666
        group: 225.6.7.8
```
