### ISSUE TITLE
In a multi-instance case,when i open the tip of healthCheck, it failed

### ISSUE THREAD

**Issue by DInTheName** [apache/servicecomb-java-chassis#2497]
In a multi-instance case,when i open the tip of healthCheck, the tip is failed,but cse-rest can work
only print:

[ INFO ]:2021-08-09 01:50:37 [main] SCBEngine:325 - Service information is shown below:
Service Center: [https://192.168.x.x:30100]
Config Center: not exist
App ID: xxx
Service Name: t-xxxx
Version: 1.0.0
Environment:
Service ID: 7954f538f77c11ebbd2d0255ac100085
Instance ID: 31442ea4f8b411eb8ab20255ac1000a5
Endpoints: ["rest://172.18.3.151:8443?sslEnabled=true"]

[ INFO ]:2021-08-09 01:50:37 [main] Application:58 - service start end...
[ INFO ]:2021-08-09 01:50:37 [registry-vert.x-worker-thread-0] ServiceRegistryClientImpl:693 - watching microservice 7954f538f77c11ebbd2d0255ac100085 successfully, the chosen service center address is 192.168.x.x:30100
 ERROR]:2021-08-09 01:51:07 [registry-vert.x-worker-thread-3] ServiceRegistryClientImpl:710 - watcher handle microservice 7954f538f77c11ebbd2d0255ac100085 response failed,

1、yaml config:

```
servicecomb:
  service:
    registry:
      address: ${cse.service.registry.address}
      instance:
        watch: true 
        healthCheck:
          interval: 30 
          times: 3
 ```

the ip  192.168.x.x  ping ok.

please help me,thanks.
