### ISSUE TITLE
使用kie可以配置push模式吗

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2641]
目前kie的配置貌似都是主动去kie拉取信息，请问有kie主动push的配置吗
```
servicecomb:
  kie:
    serverUri: http://127.0.0.1:30110
    refreshInterval: 5000
    firstRefreshInterval: 5000
    domainName: default
    enableLongPolling: true
    client:
      timeout:
        connection: 30
```
