### ISSUE TITLE
[求助] 灰度发布配置不生效

### ISSUE THREAD

**Issue by wangshiqi308** [apache/servicecomb-java-chassis#3050]
## 问题描述
我最近在尝试使用Java-chassis的灰度发布功能，我按照[灰度发布](https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/router.html)文档配置了灰度发布策略(将所有请求转发到版本号为0.0.1的服务上)，但是并没有生效，请求仍然轮询的转发到所有服务上。

## 环境
Java: 18.0.1.1
Java-chassis: v2.6.0
注册中心: [Local-CSE-2.1.4-linux-amd64.zip](https://cse-bucket.obs.cn-north-1.myhuaweicloud.com/LocalCSE/Local-CSE-2.1.4-linux-amd64.zip)
测试代码：使用的servicecomb example中的[consumer-provider](https://github.com/apache/servicecomb-samples/tree/master/basic)示例

## 灰度发布配置
在consumer的microservice.yaml中增加灰度相关配置
```
servicecomb:
  service:
    application: basic-application
    name: consumer
    version: 0.0.1
    registry:
      address: http://127.0.0.1:30100
      instance:
        watch: false

  rest:
    address: 0.0.0.0:9092

  routeRule:
    Provider: |
      - precedence: 2
        route:
          - weight: 100
            tags:
              version: 0.0.1
```
**note：routeRule为最简单的配置，这里并没有配置match规则，因为文档中提到**
![BD549EF4-8378-4211-9996-7E097026676A](https://user-images.githubusercontent.com/73977755/172886441-4778695e-089d-48ce-a1a3-7085eb9205cb.png)

并且在consumer的pom.xml中增加相关依赖项
```
<dependency>
    <groupId>org.apache.servicecomb</groupId>
    <artifactId>handler-router</artifactId>
</dependency>
<dependency>
    <groupId>org.apache.servicecomb</groupId>
    <artifactId>handler-loadbalance</artifactId>
</dependency>
```

## 实验步骤
1. 启动一个`consumer`服务，版本号设置为0.0.1，服务名为`consumer`
2. 启动两个`provider`服务，版本号分别设置为0.01和0.02，服务名为`Provider`.

provider的microservice.yaml
```
servicecomb:
  service:
    application: basic-application
    name: Provider
    version: ${version} # 0.0.1 or 0.0.2
    registry:
      address: http://127.0.0.1:30100
      instance:
        watch: false

  config:
    serverType: config-center
    serverAddr: https://127.0.0.1:30113
    fileSource: provider.yaml

  rest:
    address: 0.0.0.0:9094
```
启动好之后，可以在注册中心console中看到服务信息
![CDBA18FB-D131-4989-BB8E-CD416EDB127E](https://user-images.githubusercontent.com/73977755/172867302-8de75563-4d6f-4dde-8f65-04106e732681.png)

4. 尝试访问`consumer`服务，**请求被轮询转发到2个`provider`服务上，而不是按照我们配置的灰度策略，全部请求到0.0.1版本的Provider**

## 补充实验
为了避免`Provider`服务名与关键字有冲突，尝试将其修改。
1. 将`Provider`服务名修改为`provider`。并修改routeRule对应配置
```
routeRule:
    provider: |
      - precedence: 2
        route:
          - weight: 100
            tags:
              version: 0.0.1
```
经测试仍然不生效
3. 将`Provider`服务名修改为`serverside`
```
routeRule:
    serverside: |
      - precedence: 2
        route:
          - weight: 100
            tags:
              version: 0.0.1
```
经测试仍然不生效
