### ISSUE TITLE
Does Edge service supports routing to third party services

### ISSUE THREAD

**Issue by shri-arunraj** [apache/servicecomb-java-chassis#3189]
After registering third party service in the service center with its own name (say BusinessThirdParty) and schema, is it possible to route to this third party service dynamically with the edge configuration defined in `application.yml`

Eg

```
  http:
    dispatcher:
      edge:
        url:
          enabled: true
          mappings:
           mfaServices:
              path: "/mfa/login/.*"
              microserviceName: BusinessThirdParty
              prefixSegmentCount: 1
              versionRule: 0.0.0+
```

 I have already experimented with the invocation of this thrid party business service and it worked.
But not sure whether it is allowed route to this service dynamically Please clarify??

**Comment by liubao68** [comment]
From the perspective of edge service, if you provide the same registration information, they are the same.
If you can not provide enough information, e.g schemas,  you can also use CommonHttpDispatcher to do this.

**Comment by shri-arunraj** [comment]
@liubao68  I have an issue in that `CommonHttpDispatcher` can route to registered third party micro service , but the auth handlers configured for the third party microservice are not triggered if this dispatcher is used.
Can you help here? Why handlers are not triggered on using this dispatcher?

But for `URLMappedDispatcher` handlers are triggered but HTTP headers received in the original request are not forwarded to the destination provider on routing. 

So with `CommonHttpDispatcher` auth handlers are not triggered where as with `URLMappedDispatcher` headers are not forwarded to receipent.

Can you provide solution for either of these? Thanks in advance :)  

This is my configuration 
```
servicecomb-config-order: 100
servicecomb:
  service:
    application: m1-services
    name: gateway
    properties:
      allowCrossApp: true #whether to allow calls across applications
    version: 0.0.4
    registry:
      # Default using local service center
      address: http://localhost:30100
      instance:
        watch: false
  edge:
    filter:
      addHeader:
        enabled: true
        allowedHeaders: xxx
  handler:
    chain:
      Consumer:
        default: loadbalance,tracing-consumer
        service:
         mfa-login-service: authClientGrant,loadbalance,tracing-consumer
      Provider:
           default: bizkeeper-provider,tracing-provider
  rest:
    address: 0.0.0.0:9091?sslEnabled=false
  tracing:
    enabled: true
  http:
    dispatcher:
      edge:
        http:
          enabled: true
          order: 1
          mappings:
           oauthAdmin:
              path: "/admin/oauth/.*"
              microserviceName: oauth-service
              prefixSegmentCount: 1
              versionRule: 0.0.0+
           mfaServices:
              path: "/a/mfa/login/.*"
              microserviceName: mfa-login-service
              prefixSegmentCount: 1
              versionRule: 0.0.0+
```
