### ISSUE TITLE
CommonHttpDispatcher does not invoke handler chain and Configured Auth handler is not triggered

### ISSUE THREAD

**Issue by shri-arunraj** [apache/servicecomb-java-chassis#3201]
I have an issue in `CommonHttpDispatcher` in that the consumer auth handlers configured for the registered third party microservice are not triggered.
Can you help here? Why handlers are not triggered on using this dispatcher?

This is my configuration. Here `authClientGrant` is a consumer auth handler configured for the registered third party service `mfa-login-service` . At run time after `CommonHttpDispatcher` picks the path for routing, the request is forwarded to the `mfa-login-service` . But none of the handlers are triggered before invocation.
```
servicecomb-config-order: 100
servicecomb:
  service:
    application: m1-services
    name: gateway
    properties:
      allowCrossApp: true #whether to allow calls across applications
    version: 0.0.4
    registry:
      # Default using local service center
      address: http://localhost:30100
      instance:
        watch: false
  edge:
    filter:
      addHeader:
        enabled: true
        allowedHeaders: xxx
  handler:
    chain:
      Consumer:
        default: loadbalance,tracing-consumer
        service:
         mfa-login-service: authClientGrant,loadbalance,tracing-consumer
      Provider:
           default: bizkeeper-provider,tracing-provider
  rest:
    address: 0.0.0.0:9091?sslEnabled=false
  tracing:
    enabled: true
  http:
    dispatcher:
      edge:
        http:
          enabled: true
          order: 1
          mappings:
           oauthAdmin:
              path: "/admin/oauth/.*"
              microserviceName: oauth-service
              prefixSegmentCount: 1
              versionRule: 0.0.0+
           mfaServices:
              path: "/a/mfa/login/.*"
              microserviceName: mfa-login-service
              prefixSegmentCount: 1
              versionRule: 0.0.0+
```
