### ISSUE TITLE
同一个微服务不同shema文件的模型是否可以互相引用

### ISSUE THREAD

**Issue by beijixing511** [apache/servicecomb-java-chassis#3259]
1、在schema schema-a 文件中定义如下模型
```
  GpcsRet:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "返回码"
      msg:
        type: "string"
        description: "返回描述"
    x-java-class: "com.huawei.game.gpcs.model.common.GpcsRet"
```

2、是否可以在schema B 文件中如下引用
```
  CommonRsp:
    type: "object"
    properties:
      ret:
        $ref: "schema-a.yaml#/definitions/GpcsRet"
````
