### ISSUE TITLE
新老灰度发布配置不兼容？请确认生效逻辑

### ISSUE THREAD

**Issue by little-cui** [apache/servicecomb-java-chassis#3709]
**场景**：由于老版本框架配置的是cse开头的配置来控制灰度发布规则，升级框架后，客户按新的[配置方式](https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/router.html)增加新的灰度规则。

配置项1：cse.darklaunch.policy.weather
```json
{
  "policyType": "RULE",
  "ruleItems": [
    {
      "groupName": "self_rule_656473",
      "groupCondition": "version=0.0.3",
      "policyCondition": "city=beijing",
      "versions": [
        "0.0.3"
      ]
    }
  ],
  "empty": false
}
```

配置项2：servicecomb.routeRule.weather
```yaml
---
- precedence: 1
  route:
  - weight: 100
    tags:
      version: "0.0.2"
- precedence: 2
  match:
    headers:
      city:
        exact: "chengdu"
        caseInsensitive: false
  route:
  - weight: 100
    tags:
      version: "0.0.3"
```

**预期**
1、city=beijing流量100%转发到灰度版本0.0.3
2、city=chengdu流量100%转发到灰度版本0.0.3
3、其他100%转发到版本0.0.2
**实际**
1、city=beijing流量100%转发到版本0.0.2
2、city=chengdu流量100%转发到版本0.0.2
3、其他100%转发到版本0.0.2

**框架版本**：2.7.9
