### ISSUE TITLE
servlet.urlPattern is not effect when bind to additionalPorts

### ISSUE THREAD

**Issue by lalicw** [apache/servicecomb-java-chassis#3917]
we use java-chassis-spring-boot-starter-servlet

and we config like this in the yml file:

```yaml
# spring boot configurations
server:
  port: 9092  # should be same with servicecomb.rest.address to use web container
  additionalPorts: 8082

servicecomb:
    rest:
      servlet:
        urlPattern: /rest/*
      address: 0.0.0.0:8082  # use the additionalPorts
    provider:
      rest:
        scanRestController: false
```

but the urlPattern is not effect， we can just use this url to access the service.
http://localhost:8082/sayHello?name=XXX

but we expect this
http://localhost:8082/rest/sayHello?name=XXX
