### ISSUE TITLE
使用本地注册机制，在跨服务场景下2.8.x版本加载契约文件目录与预期不符

### ISSUE THREAD

**Issue by JedrekWang** [apache/servicecomb-java-chassis#4375]
#### 背景
基于local.registry.file环境变量使用本地注册能力
构造跨服务调用场景，配置如下：
```yaml
"BizService:BizMicroservice":
  - version: 0.0.3
    appid: BizService
    schemaIds:
      - schema1
    instances:
      - endpoints:
          - rest://127.0.0.1:${port}
```

调度代码如下：

```java
@RpcReference(microserviceName = "BizService:BizMicroservice", schemaId = "schema1")
    ProviderFacade providerFacade;
```

servicecomb 2.8.x 代码org.apache.servicecomb.registry.swagger.SwaggerLoader#loadSwagger调用loadLocalSwagger加载本地契约方法时，传递的微服务名使用的是**microservice.getServiceName()**，这个名称为“BizService:BizMicroservice”，与预期的shortName即“BizMicroservice“不符

对比servicecomb 1.x代码org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory#generateSchemaPath方法中专门切分获取到了微服务名*String realMicroserviceName = microserviceName.substring(idxAt + 1);*

#### 导致问题
因为本地文件创建不能带有冒号：，这个变化导致跨服务调用场景无法加载到契约文件，且无法规避处理

#### 诉求
这个是否为2.8.x的问题？能否参考1.x的方式加载契约文件使用的微服务名额外做冒号切分处理

**Comment by liubao68** [comment]
```
BizMicroservice:
  - version: 0.0.3
    appid: BizService
    schemaIds:
      - schema1
    instances:
      - endpoints:
          - rest://127.0.0.1:${port}
```

实际是不是想要这样？
