### ISSUE TITLE
网关转发的疑问

### ISSUE THREAD

**Issue by louie-24** [apache/servicecomb-java-chassis#4593]
环境edge作为网关，nacos作为注册中心，在使用中发现，如果服务增加了新的接口，需要重启网关才能路由到最新的接口，请问如果增加新接口后不重启网关的话需要如何进行配置呢

**Comment by liubao68** [comment]
参考: https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/definition/service-definition.html 接口变化更新下版本号即可。 

```
servicecomb:
  service:
    application: helloTest
    name: helloServer 
    version: 0.0.1 
```
