### ISSUE TITLE
重试策略不生效

### ISSUE THREAD

**Issue by zouxiaoqiang** [apache/servicecomb-java-chassis#4671]
servicecomb版本：2.7.8
重试策略配置：
```
loadbalance:
  retryEnabled: true
  retryOnNext: 1
  retryOnSame: 0
```
构造场景：A服务访问B1、B2服务，其中B1服务网络访问不通
我们调用单个请求失败，预期应该是可以成功的
定位发现：
`InvokerUtils.canRetryForException`方法返回true
![3173981C-ECFD-4132-D791-FF187F29E335](https://github.com/user-attachments/assets/bbbc12bc-ad02-4435-be5b-448102156a1f)
`InvokerUtils.updateRetryStatus`方法只被调用一次，且走不到`invocation.isFinished()`的判断中
